version: '3'

services:
  php:
    container_name: php
    build: ./docker/php
    volumes:
    - ./:/var/www

  nginx:
    image: nginx
    container_name: nginx
    ports:
    - 80:80
    volumes:
    - ./:/var/www
    - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
    - php

  db:
    image: mysql:5.7
    container_name: db-host
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: database
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      TZ: 'Azia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
    - ./docker/db/data:/var/lib/mysql
    - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
    - ./docker/db/sql:/docker-entrypoint-initdb.d
    ports:
    - 3306:3306

  selenium:
    container_name: chrome
    image: selenium/standalone-chrome
    ports:
      - 4444:4444
    # mysql_test:
    #   image: mysql:5.7
    #   container_name: test_db-host
    #   environment:
    #     MYSQL_ROOT_PASSWORD: root
    #     MYSQL_DATABASE: database
    #     MYSQL_USER: docker
    #     MYSQL_PASSWORD: docker
    #     TZ: 'Azia/Tokyo'
    #   command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    #   volumes:
    #   - ./docker/db/data:/var/lib/mysql
    #   - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
    #   - ./docker/db/sql:/docker-entrypoint-initdb.d
    #   ports:
    #   - 3306:3306
  